version: '3'

services:
  userservice:
    build:
      context: ./userservice
    container_name: shoplify-userservice
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - 8081:8081