# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0


receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"

exporters:
  otlphttp/aware:
    endpoint: "https://ingress-staging.awarelabs.io"
    headers: {"x-aware-project-id": "3cc5e2fb-80d6-4c4b-9ab1-98cf6da202f1"}
  logging:

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging,otlphttp/aware]
