steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-west4-docker.pkg.dev/testchimp/tc-image-repo/shoplify-frontendservice:latest'
      - '-f'
      - 'dockerfile-staging'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-west4-docker.pkg.dev/testchimp/tc-image-repo/shoplify-frontendservice:latest'
images:
  - 'us-west4-docker.pkg.dev/testchimp/tc-image-repo/shoplify-frontendservice:latest'
