/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
}

repositories {
    mavenCentral()
}

version = "0.0.1-SNAPSHOT"
java.sourceCompatibility = JavaVersion.VERSION_1_8

dependencies {
    implementation("com.google.protobuf:protobuf-java:3.21.12")
    implementation("com.google.protobuf:protobuf-java-util:3.21.12")
}
