# Use the official Node.js image
FROM node:14

# Create and change to the app directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Set OpenTelemetry environment variables
ENV OTEL_SERVICE_NAME=riskservice
ENV OTEL_RESOURCE_ATTRIBUTES="service.namespace=shoplify,deployment.environment=staging,service.version=riskservice.2024.05.13.01"
ENV OTEL_EXPORTER_OTLP_ENDPOINT="http://shoplify_collector:4317"
ENV OTEL_EXPORTER_OTLP_PROTOCOL=grpc
ENV OTEL_INSTRUMENTATION_COMMON_EXPERIMENTAL_CONTROLLER_TELEMETRY_ENABLED=true

# Expose the port the app runs on
EXPOSE 8084

# Define the command to run the app
CMD ["node", "--require", "./tracer.js", "index.js"]

